1. Create two random 3x3 matrices (A and B).
2. Perform element-wise addition, subtraction, multiplication, and division on these matrices.
3. Compute the dot product of A and the transpose of B.

In [7]:
import numpy as np

A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

print("Matrix 1:\n", A)
print("Matrix 2:\n", B)

print("Element-wise addition:\n", A + B)
print("Element-wise subtraction:\n", A - B)
print("Element-wise multiplication:\n", A * B)
print("Element-wise division:\n", A / B)

print("Dot product of A and the transpose of B:\n", np.dot(A, B.transpose()))

Matrix 1:
 [[0.6853979  0.92155348 0.53270732]
 [0.46919595 0.73935332 0.72635345]
 [0.21802325 0.95113037 0.05025699]]
Matrix 2:
 [[0.57992723 0.32627078 0.77357397]
 [0.70887651 0.69865214 0.51302687]
 [0.14326906 0.91301505 0.68615156]]
Element-wise addition:
 [[1.26532514 1.24782426 1.30628129]
 [1.17807246 1.43800546 1.23938032]
 [0.3612923  1.86414542 0.73640854]]
Element-wise subtraction:
 [[ 0.10547067  0.59528271 -0.24086665]
 [-0.23968056  0.04070118  0.21332658]
 [ 0.07475419  0.03811532 -0.63589457]]
Element-wise multiplication:
 [[0.39748091 0.30067597 0.41208852]
 [0.33260199 0.51655078 0.37263884]
 [0.03123599 0.86839635 0.03448391]]
Element-wise division:
 [[1.1818688  2.82450514 0.68863139]
 [0.66188673 1.05825672 1.41581949]
 [1.52177483 1.04174665 0.07324473]]
Dot product of A and the transpose of B:
 [[1.11024539 1.40300096 1.30510647]
 [1.07521701 1.22179161 1.24065052]
 [0.47564116 0.84484402 0.93411624]]


Generate a NumPy array with integers from 0 to 20.
Extract all even numbers using array slicing.
Replace all odd numbers with -1.

In [31]:
Array1=np.arange(0,21)
even=Array1[0::2]
Array1[1::2]=[-1]

print("Even:",even)
print("Replaced all odd numbers with -1:\n", Array1)

Even: [ 0  2  4  6  8 10 12 14 16 18 20]
Replaced all odd numbers with -1:
 [ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20]


Create a random 1D array with 100 elements.
Calculate the mean, median, and standard deviation of the array.
Identify the index of the maximum and minimum values in the array.

In [41]:
import numpy as np

Array2 = np.random.rand(100)

mean_value = np.mean(Array2)
median_value = np.median(Array2)
std_deviation = np.std(Array2)

max_index = np.argmax(Array2)
min_index = np.argmin(Array2)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)
print("Index of Maximum Value:", max_index)
print("Index of Minimum Value:", min_index)

Mean: 0.514108902530414
Median: 0.5018705504992441
Standard Deviation: 0.2564606485899161
Index of Maximum Value: 95
Index of Minimum Value: 69
